apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: dapr-config
spec:
  tracing:
    samplingRate: "1"
    stdout: true
  features:
    - name: "conversation"
      enabled: true
  accessControl:
    defaultAction: allow