# Dapr Redis State Store Component for Session and Cache Data
# This component handles temporary data, session state, and caching

apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore-cache
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: "localhost:6379"
  - name: redisPassword
    value: ""
  - name: redisDB
    value: "2"
  - name: actorStateStore
    value: "false"
  - name: keyPrefix
    value: "cache"
  - name: ttlInSeconds
    value: "3600"
scopes:
- dapr-agents