# Dapr State Store Component for Workflows and Actors
# This component enables workflow and actor state persistence

apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.in-memory
  version: v1
  metadata:
  - name: actorStateStore
    value: "true"
scopes:
- dapr-agents