# Dapr Redis State Store Component for Workflows and Actors
# This component enables workflow and actor state persistence using Redis

apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore-workflows
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: "localhost:6379"
  - name: redisPassword
    value: ""
  - name: redisDB
    value: "0"
  - name: actorStateStore
    value: "true"
  - name: keyPrefix
    value: "workflows"
scopes:
- dapr-agents